// Auto-generated by `npx convex dev`. This stub allows TypeScript to compile
// before a Convex deployment is configured. Run `npx convex dev` to replace.
/* eslint-disable @typescript-eslint/no-explicit-any */

import type { AnyApi } from "convex/server";

declare const api: AnyApi;
declare const internal: AnyApi;
export { api, internal };
