// Auto-generated by `npx convex dev`. This stub allows TypeScript to compile
// before a Convex deployment is configured. Run `npx convex dev` to replace.

import type { GenericId } from "convex/values";

export type Id<TableName extends string> = GenericId<TableName>;
