// Auto-generated by `npx convex dev`. This stub allows TypeScript to compile
// before a Convex deployment is configured. Run `npx convex dev` to replace.

export { mutation, query, internalMutation } from "convex/server";
