// Auto-generated by `npx convex dev`. Stub for pre-deployment compilation.
const { mutation, query, internalMutation } = require("convex/server");
module.exports = { mutation, query, internalMutation };
